### ISSUE TITLE
Applying for reprint permission. 

### ISSUE THREAD

**Issue by jwjoel** [randombyte-developer/command-utils#11]
Thanks for your contribute! The plugin is awesome and it really helps me a lot. Whether can I reprint the plugin to another Chinese Minecraft forum with all copyright information. I'll make a redirect to the Ore page. Waiting for your reply :)

**Comment by randombyte-developer** [comment]
Hi!

You can do that, please also provide the link to this page https://github.com/randombyte-developer/command-utils

When you're done, can you post the link to your page in here?
