### ISSUE TITLE
Var %player% doesn't work on aliases

### ISSUE THREAD

**Issue by Yoshun** [randombyte-developer/command-utils#14]
Hi there !

I have a problem with your command-utils plugin :
I want to recover the player nickname with % player% to create a custom command with aliases.conf file. But% player% does not seem to work : "[Server thread/INFO] [minecraft/DedicatedServer]: Player '%player%' cannot be found"

Can you help me ?
My server using last recommended SpongeForge build : 1.12.2-2838-7.1.8

My aliases.conf file :

aliases {
    vote {
    	commands=[
    		"*say hi %player%"
    	]
    	permission="command-utils.vote"
    }
}

Thanks and sorry for my english ^^

**Comment by randombyte-developer** [comment]
Use this version https://github.com/randombyte-developer/PlaceholderAPI/releases/

**Comment by Yoshun** [comment]
Perfect, it's working !
Thank you :)
