### ISSUE TITLE
Make *-command run as an OP instead of console

### ISSUE THREAD

**Issue by asdfasdfsg** [randombyte-developer/command-utils#15]
For example if I want a user to execute alias for WorldEdit command //chunk current implementation will run this command in a console and nothing will happen for the user. There are plenty of other cases of OP-running command benefits.

**Comment by randombyte-developer** [comment]
Only a player can be OP. So you want the player to temporarily have the permission to execute the command? LuckPerms already has something like this implemented. 
https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Permission#lp-usergroup-usergroup-permission-settemp-node-truefalse-duration-temporary-modifier-context

Specify a short duration like 3 seconds to revoke the permission.

**Comment by randombyte-developer** [comment]
Closed due to inactivity.
