### ISSUE TITLE
Tab complete player names

### ISSUE THREAD

**Issue by aWitch-Doctor** [randombyte-developer/command-utils#5]
Is there any way you can make it so when tab is hit it will try to complete a player name? Start with "wi" hit tab and it shows online players first whose name starts with "wi". If I keep hitting tab I start getting names of offline people from a list nucleus or sponge has.

**Comment by randombyte-developer** [comment]
That's currently not possible. It is on my todo list.

**Comment by randombyte-developer** [comment]
Possible with [KtSkript](https://github.com/randombyte-developer/kt-skript).
