### ISSUE TITLE
Possible conflict with griefprevention.

### ISSUE THREAD

**Issue by Corcustos** [randombyte-developer/command-utils#6]
https://github.com/MinecraftPortCentral/GriefPrevention/issues/663 For some reason commandutils was spamming errors in my config and causing issues with griefprevention.

My recent logs and a description of the problem can be found in the above issue.

**Comment by randombyte-developer** [comment]
The command utils config isn't valid. Read line 231 of latest.log. (can't cite it because I'm on mobile)

Follow the instruction there to correct your config.

**Comment by Corcustos** [comment]
I was able to resolve the commandutils problem, and it seemingly has no relation to griefprevention anymore. 'twas a user error.
