### ISSUE TITLE
[REQUEST] Add test for item in inventory not just in hand

### ISSUE THREAD

**Issue by SirFancyBacon** [randombyte-developer/command-utils#8]
Add a command that tests for an item and it's quantity within the players inventory, similar to the existing
`/cu has in hand <playerName>|<playerUuid> <item> [quantity = 1]`
and
`/cu has given from hand <playerName>|<playerUuid> <item> [quantity = 1]`

**Comment by randombyte-developer** [comment]
Added in https://github.com/randombyte-developer/command-utils/releases/tag/v2.4.0
